# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Radiant Content GUI.

Build mode is **onedir** rather than onefile: onefile extracts the
whole bundle to a temp dir on every launch and is noticeably slower.
The 30-80 MB onedir folder ships inside the Inno Setup installer, so
end users still see a single download.

What this spec sets up:

* The entry point ``gui/__main__.py`` (so ``python -m gui`` and the
  frozen ``.exe`` share an identical bootstrap).
* The Qt theme file ``gui/theme.qss`` and the app icon are bundled
  as data files.
* The Windows VERSIONINFO resource is read from
  ``packaging/version_info.txt`` (regenerated by
  ``scripts/stamp_version.py``).
* ``hiddenimports`` lists modules PyInstaller's static analyser
  cannot see at all (keyring backends are dynamically discovered;
  pydantic v2 ships a few JIT-style internals; ``git.refs`` is
  lazy-loaded by GitPython).

Build locally:

    pwsh packaging/build_app.ps1

Or directly:

    pyinstaller packaging/radiant_content_gui.spec --noconfirm --clean
"""

from pathlib import Path

# Locate the repo root from this spec file. ``__file__`` is not
# defined inside a PyInstaller spec at execution time, but
# ``SPEC`` is (it's the absolute path to the .spec file).
SPEC_PATH = Path(SPEC).resolve()  # noqa: F821 - injected by PyInstaller
PROJECT_ROOT = SPEC_PATH.parent.parent
PACKAGING = PROJECT_ROOT / "packaging"
GUI = PROJECT_ROOT / "gui"

ICON_PATH = PACKAGING / "icon.ico"
VERSION_INFO_PATH = PACKAGING / "version_info.txt"


block_cipher = None


datas = [
    # The Qt stylesheet is loaded by ``gui/app.py`` from the package
    # directory; bundle it next to the package so the lookup works
    # inside the frozen environment too.
    (str(GUI / "theme.qss"), "gui"),
    # Bundle the icon at the root so a future "About" or tray menu
    # can locate it via ``sys._MEIPASS``.
    (str(ICON_PATH), "."),
]


hiddenimports = [
    # pydantic v2 hot-loads parts of its internal core that the
    # PyInstaller AST scanner doesn't see.
    "pydantic._internal._core_utils",
    "pydantic._internal._model_construction",
    "pydantic.deprecated.decorator",

    # keyring discovers its backend at runtime via entry points; the
    # static scanner can't follow that, so name every OS backend we
    # might possibly need. Bundling the unused ones costs ~50 KB
    # each and means the same .spec works on every platform.
    "keyring.backends.Windows",
    "keyring.backends.macOS",
    "keyring.backends.SecretService",
    "keyring.backends.chainer",
    "keyring.backends.fail",
    "keyring.backends.null",

    # GitPython lazy-imports these submodules on first use.
    "git.refs",
    "git.refs.head",
    "git.refs.log",
    "git.refs.reference",
    "git.refs.remote",
    "git.refs.tag",

    # Qt sub-modules that get pulled in transitively but are
    # sometimes missed by the analyser when the import is buried
    # behind an attribute access.
    "PySide6.QtSvg",
    "PySide6.QtNetwork",
]


a = Analysis(
    [str(GUI / "__main__.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Common-but-large modules we never use; excluding them
        # trims tens of megabytes from the bundle.
        "tkinter",
        "test",
        "unittest",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="RadiantContentGUI",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # UPX trips antivirus heuristics; skip it.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ICON_PATH),
    version=str(VERSION_INFO_PATH),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="RadiantContentGUI",
)
