# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Radiant Content GUI - Windows and macOS.

Build mode is **onedir** rather than onefile: onefile extracts the
whole bundle to a temp dir on every launch and is noticeably slower.
On Windows the onedir folder ships inside the Inno Setup installer;
on macOS it is wrapped in a ``.app`` BUNDLE which is then dropped
into a DMG. End users on either OS still see a single download.

What this spec sets up:

* The entry point ``gui/__main__.py`` (so ``python -m gui`` and the
  frozen executable share an identical bootstrap).
* The Qt theme file ``gui/theme.qss`` and the app icon are bundled
  as data files.
* Per-OS branches at the bottom: Windows produces a ``.exe`` plus
  the COLLECT directory; macOS additionally wraps COLLECT in a
  ``.app`` via BUNDLE.
* The Windows VERSIONINFO resource is read from
  ``packaging/version_info.txt`` (regenerated by
  ``scripts/stamp_version.py``). On macOS that file is ignored;
  the version is injected into the bundle's ``Info.plist`` instead.
* ``hiddenimports`` lists modules PyInstaller's static analyser
  cannot see at all (keyring backends are dynamically discovered;
  pydantic v2 ships a few JIT-style internals; ``git.refs`` is
  lazy-loaded by GitPython).

Build locally:

    # Windows
    pwsh packaging/build_app.ps1
    # macOS
    bash packaging/build_app.sh

Or directly (works on both OSes):

    pyinstaller packaging/radiant_content_gui.spec --noconfirm --clean
"""

import sys
from pathlib import Path

# Locate the repo root from this spec file. ``__file__`` is not
# defined inside a PyInstaller spec at execution time, but
# ``SPEC`` is (it's the absolute path to the .spec file).
SPEC_PATH = Path(SPEC).resolve()  # noqa: F821 - injected by PyInstaller
PROJECT_ROOT = SPEC_PATH.parent.parent
PACKAGING = PROJECT_ROOT / "packaging"
GUI = PROJECT_ROOT / "gui"

IS_MACOS = sys.platform == "darwin"
IS_WINDOWS = sys.platform.startswith("win")

# Pick the platform-appropriate icon. Both files live in the same
# folder so swapping a real Radiant logo later means dropping two
# files (.ico for Windows, .icns for macOS) and we are done.
WIN_ICON_PATH = PACKAGING / "icon.ico"
MAC_ICON_PATH = PACKAGING / "icon.icns"
PRIMARY_ICON = MAC_ICON_PATH if IS_MACOS else WIN_ICON_PATH

VERSION_INFO_PATH = PACKAGING / "version_info.txt"


# ---------------------------------------------------------------------------
# Read the app version from the single source of truth so the macOS
# Info.plist stays in lock-step with the Windows VERSIONINFO without
# any manual stamping. ``scripts/stamp_version.py`` rewrites this
# file in CI right before the build runs.
# ---------------------------------------------------------------------------

def _read_app_version() -> str:
    """Return ``__version__`` from ``gui/__version__.py``.

    Done with a regex rather than ``import`` so the spec stays
    dependency-free and does not have to put the project on
    ``sys.path`` at spec-eval time.
    """
    import re

    text = (GUI / "__version__.py").read_text(encoding="utf-8")
    match = re.search(
        r'^\s*__version__\s*:\s*str\s*=\s*[\'"]([^\'"]+)[\'"]',
        text,
        re.MULTILINE,
    )
    if not match:
        match = re.search(
            r'^\s*__version__\s*=\s*[\'"]([^\'"]+)[\'"]',
            text,
            re.MULTILINE,
        )
    return match.group(1) if match else "0.0.0"


APP_VERSION = _read_app_version()


block_cipher = None


# All data files we want to land *inside* the bundle, regardless of
# OS. The Qt stylesheet is looked up at runtime by ``gui/app.py``;
# bundling the icon lets a future tray menu or About dialog show it.
datas = [
    (str(GUI / "theme.qss"), "gui"),
    (str(PRIMARY_ICON), "."),
]


hiddenimports = [
    # pydantic v2 hot-loads parts of its internal core that the
    # PyInstaller AST scanner does not see.
    "pydantic._internal._core_utils",
    "pydantic._internal._model_construction",
    "pydantic.deprecated.decorator",

    # keyring discovers its backend at runtime via entry points; the
    # static scanner cannot follow that, so name every OS backend
    # we might possibly need. Bundling the unused ones costs ~50 KB
    # each and means the same .spec works on every platform.
    "keyring.backends.Windows",
    "keyring.backends.macOS",
    "keyring.backends.SecretService",
    "keyring.backends.chainer",
    "keyring.backends.fail",
    "keyring.backends.null",

    # GitPython lazy-imports these submodules on first use.
    "git.refs",
    "git.refs.head",
    "git.refs.log",
    "git.refs.reference",
    "git.refs.remote",
    "git.refs.tag",

    # Qt sub-modules pulled in transitively but sometimes missed by
    # the analyser when the import is buried behind attribute access.
    "PySide6.QtSvg",
    "PySide6.QtNetwork",
]


a = Analysis(
    [str(GUI / "__main__.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Common-but-large modules we never use; excluding them
        # trims tens of megabytes from the bundle.
        "tkinter",
        "test",
        "unittest",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)


# ---------------------------------------------------------------------------
# Per-OS EXE / BUNDLE configuration.
#
# Windows: a single ``.exe`` with a VERSIONINFO resource baked in.
# macOS:   a fat (universal2) Mach-O launcher that gets wrapped in
#          a ``.app`` BUNDLE below. ``target_arch='universal2'``
#          tells PyInstaller to splice arm64 + x86_64 slices into
#          every bundled dylib it can; the GitHub macos-latest
#          runner ships a universal2 Python so the result is a
#          real universal binary that runs natively on both
#          Apple Silicon and Intel Macs.
# ---------------------------------------------------------------------------

exe_kwargs = dict(
    name="RadiantContentGUI",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # UPX trips antivirus heuristics; skip it.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(PRIMARY_ICON),
)

if IS_WINDOWS:
    exe_kwargs["version"] = str(VERSION_INFO_PATH)
    exe_kwargs["target_arch"] = None
elif IS_MACOS:
    # Universal2 covers every Mac sold since 2006 in a single binary;
    # the size hit (~2x for the launcher itself, but much less in
    # percentage terms once Qt frameworks are added) is worth not
    # having to publish two separate downloads.
    exe_kwargs["target_arch"] = "universal2"

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    **exe_kwargs,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="RadiantContentGUI",
)


if IS_MACOS:
    # BUNDLE wraps the COLLECT directory in a proper ``.app`` shell
    # with Contents/MacOS, Contents/Frameworks, and Contents/Resources.
    # Without BUNDLE, macOS would treat the directory as a plain
    # folder, the icon would not show in Finder, double-click would
    # not launch the app, and the Dock would refuse to display it.
    app = BUNDLE(
        coll,
        name="RadiantContentGUI.app",
        icon=str(MAC_ICON_PATH),
        bundle_identifier="edu.nau.radiant.contentgui",
        # CFBundleShortVersionString is what Finder's Get Info and
        # the App Store-style "About this Mac" presentation show.
        # CFBundleVersion is the build number macOS uses for
        # update comparisons - we use the same value so the app's
        # version is unambiguous.
        version=APP_VERSION,
        info_plist={
            "CFBundleName": "Radiant Content GUI",
            "CFBundleDisplayName": "Radiant Content GUI",
            "CFBundleShortVersionString": APP_VERSION,
            "CFBundleVersion": APP_VERSION,
            # Retina / hi-DPI rendering. Without this every Qt
            # widget would be drawn at 1x and upscaled, which looks
            # blurry on every Mac sold in the last decade.
            "NSHighResolutionCapable": True,
            # Big Sur is the earliest release that ships natively
            # for Apple Silicon, which matches our universal2
            # binary's runtime expectations.
            "LSMinimumSystemVersion": "11.0",
            # Plain GUI app (not a background daemon, not a faceless
            # menu-bar agent). ``False`` => normal Dock + menu bar.
            "LSUIElement": False,
            "NSHumanReadableCopyright": (
                "Copyright (c) Radiant Center for Remote Sensing"
            ),
            # Tell macOS the app does not need any privacy-prompted
            # services. Keeping this conservative (no camera, mic,
            # location, etc.) avoids the "RadiantContentGUI wants
            # to access..." popups that confuse first-time users.
        },
    )
